name = "aquamarine"
version = "0.1.0"
description = "Protocol-agnostic Beryl-style channel client runtime for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "tylerbutler", repo = "aquamarine" }
gleam = ">= 1.18.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.48.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
logging = ">= 1.5.0 and < 2.0.0"
collie = ">= 3.0.0 and < 4.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
roost = { git = "https://github.com/tylerbutler/roost.git", ref = "7e4dc7c327ec233c9dc22a9d2037a620e700e127" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
beryl = { git = "https://github.com/tylerbutler/beryl.git", ref = "81f799eb838d0c30ba089e41899282e82c3ccd49", path = "packages/beryl" }
beryl_mist = { git = "https://github.com/tylerbutler/beryl.git", ref = "81f799eb838d0c30ba089e41899282e82c3ccd49", path = "packages/beryl_mist" }
mist = ">= 6.0.0 and < 7.0.0"
phoenix_channel_fixtures = { git = "https://github.com/tylerbutler/phoenix_channel_fixtures.git", ref = "7daccb856d17db6278980277237c201b2acdcdf1" }
